# 예외처리



## 예외란

- 프로그램에 문제가 있는 것을 말함
- 예외로 인해 시스템 동작이 멈추는 것을 막는 것을 '예외처리' 라고함
- Exception과 Error의 차이
  - Exception
    - 개발자가 코드로 대처할 수 있음
  - Error
    - 시스템에서 발생, 개발자가 대처할 수 없음
    - 예를들어 JVM에 문제가 있다든가.. 메모리가 부족하다든가.. 물리적으로 전력이 차단됐다든가..
- Exception
  - Checked Exception
    - 예외처리를 반드시 해야하는 경우
    - 네트워크, 파일 시스템 등
      - 만약 예외처리 안하면 컴파일이 안됨
  - Unchecked Exception
    - 예외처리를 개발자의 판단에 맞기는 경우
    - 데이터 오류 등



## Exception 클래스

- Exception
  - NullPointerException
    - 객체를 가리키지 않고 있는 레퍼런스를 이용할 때
  - ArrayIndexOutOfBoundException
    - 배열에서 존재하지 않는 인덱스를 가리킬 때
  - NumberFormatException
    - 숫자데이터에 문자데이터등을 넣었을 때
  - 등등등...많은 childclass 존재



## try catch

```java
try {
    예외가 발생할 수 있는 코드
} catch (Exception e) {
    예외가 발생했을 때 처리할 코드
}
```

- 예시

```java
public class MainClass {

    public static void main(String[] args) {

        int i = 10;
        int j = 0;
        int k = 0;

        System.out.println("Exception Before");

        try {
            k = i / j;
        } catch (Exception e) {
            // 어떤 예외가 발생했는지 콘솔에 출력
            e.printStackTrace();
            // 예외를 간략하게 나타낸 문자열을 보내줌
            String msg = e.getMessage();
            System.out.println("Exception : " + msg);
        }
    }
    
}

// 결과
/*
Exception Before
java.lang.ArithmeticException: / by zero
	at MainClass.main(MainClass.java:14)
Exception : / by zero
*/
```



## 다양한 예외처리

- Exception 및 하위 클래스를 이용해 예외처리를 다양하게 할 수 있음

```java
import java.util.ArrayList;
import java.util.InputMismatchException;
import java.util.Scanner;

public class MainClass {

    public static void main(String[] args) {

        // case 1
        Scanner scanner = new Scanner(System.in);
        int i, j;

        // case 2
        int[] iArr = {0, 1, 2, 3, 4};

        // case 3
        ArrayList<String> list = null;

        System.out.println("Exception BEFORE");

        try {
            // case 1
            System.out.println("input i : ");
            i = scanner.nextInt();
            System.out.println("input j : ");
            j = scanner.nextInt();
            System.out.println("i / j = " + (i / j));

            // case 2
            for (int k = 0; k < 5; k++) {
                System.out.println("iArr[" + k + "] : " + iArr[k]);
            }

            // case 3
            System.out.println("list.size() : " + list.size());

        } catch (InputMismatchException e) {
            // case 1
            e.printStackTrace();
        } catch (ArrayIndexOutOfBoundsException e) {
            // case 2
            e.printStackTrace();
        } catch (Exception e) {
            // case 3
            e.printStackTrace();
        }

        System.out.println("Exception AFTER");
    }

}

```

- try 문 안의 case 1에서 예외 발생 시 catch로 넘어가서 catch문 이후의 코드가 실행됨
  - 즉, try문 안에서 예외가 발생한 코드의 아래에 있는 코드는 실행되지 않고 해당하는 catch문으로 바로 넘어감 



## finally

- 예외 발생 여부에 상관없이 반드시 실행
- try - catch문 가장 아래에 `finally {실행할 코드}`로 작성



## throws

- 예외 발생 시 예외처리를 직접 하지 않고 호출한 곳으로 넘김

```java
public class MainClass {

    public static void main(String[] args) {

        MainClass m = new MainClass();
        
        // 4. 여기서 예외 처리
        try {
            m.first();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    // 3. second로 부터 throw를 받아서 호출한 곳으로 throw
    public void first() throws Exception {
        second();
    }

    // 2. third로 부터 throw를 받아서 호출한 곳으로 throw
    public void second() throws Exception {
        third();
    }

    public void third() throws Exception {
        // 1. 예외발생, third를 호출한 곳으로 throw
        System.out.println("10 / 0  = " + ( 10 / 0 ));
    }

}
```

